// lib/gradeList.ts
// All PlayHQ grade IDs to sync fixtures for.
// Mirrors the leagueMap from the website. Add/remove grades here as needed.

export interface GradeEntry {
  gradeId: string
  competition: string
  grade: string
}

export const GRADE_LIST: GradeEntry[] = [
  // SANFL
  { gradeId: 'e85894b8', competition: 'SANFL', grade: 'League' },
  { gradeId: 'e765432b', competition: 'SANFL', grade: 'Reserves' },
  { gradeId: '19b30dd1', competition: 'SANFL', grade: 'Under 18' },
  { gradeId: '46b49907', competition: 'SANFL', grade: 'Under 16' },

  // SANFLW
  { gradeId: '63232818', competition: 'SANFLW', grade: 'League' },

  // Amateurs (Men's) — League
  { gradeId: '8eecd4b0', competition: "Amateurs (Men's)", grade: 'Division 1' },
  { gradeId: '85247b82', competition: "Amateurs (Men's)", grade: 'Division 2' },
  { gradeId: '372b55e9', competition: "Amateurs (Men's)", grade: 'Division 3' },
  { gradeId: '22794d03', competition: "Amateurs (Men's)", grade: 'Division 4' },
  { gradeId: '372d8776', competition: "Amateurs (Men's)", grade: 'Division 5' },
  { gradeId: '961ce426', competition: "Amateurs (Men's)", grade: 'Division 6' },
  { gradeId: '43b5cc78', competition: "Amateurs (Men's)", grade: 'Division 7' },
  // Amateurs — Reserves
  { gradeId: '1f82c881', competition: "Amateurs (Men's)", grade: 'Division 1 Reserves' },
  { gradeId: '8ebba3c8', competition: "Amateurs (Men's)", grade: 'Division 2 Reserves' },
  { gradeId: 'b9156c34', competition: "Amateurs (Men's)", grade: 'Division 3 Reserves' },
  { gradeId: '692c9b17', competition: "Amateurs (Men's)", grade: 'Division 4 Reserves' },
  { gradeId: 'cedbc98d', competition: "Amateurs (Men's)", grade: 'Division 5 Reserves' },
  { gradeId: '3beb6a9e', competition: "Amateurs (Men's)", grade: 'Division 6 Reserves' },
  { gradeId: '1991ba25', competition: "Amateurs (Men's)", grade: 'Division 7 Reserves' },
  // Amateurs — C-Grade
  { gradeId: 'd7fe9dd5', competition: "Amateurs (Men's)", grade: 'Division C1' },
  { gradeId: 'aea638ff', competition: "Amateurs (Men's)", grade: 'Division C2' },
  { gradeId: '256a623b', competition: "Amateurs (Men's)", grade: 'Division C3' },
  { gradeId: '1bd8ff22', competition: "Amateurs (Men's)", grade: 'Division C4' },
  { gradeId: '792996a6', competition: "Amateurs (Men's)", grade: 'Division C5' },
  { gradeId: 'a645b2ca', competition: "Amateurs (Men's)", grade: 'Division C6' },
  { gradeId: '69f075a6', competition: "Amateurs (Men's)", grade: 'Division C7' },
  { gradeId: 'a374a910', competition: "Amateurs (Men's)", grade: 'Division C8' },

  // SAWFL Women's
  { gradeId: '012b743d', competition: "SAWFL Women's", grade: 'Division 1' },
  { gradeId: 'c54fb997', competition: "SAWFL Women's", grade: 'Division 2' },
  { gradeId: '68158f54', competition: "SAWFL Women's", grade: 'Division 3' },
  { gradeId: 'c7355be5', competition: "SAWFL Women's", grade: 'Division 4' },
  { gradeId: '387394cc', competition: "SAWFL Women's", grade: 'Division 5' },
  { gradeId: '629dbe72', competition: "SAWFL Women's", grade: 'Division 6' },
  { gradeId: '56ad9865', competition: "SAWFL Women's", grade: 'Division 1 Reserves' },
  { gradeId: '0d9cc3ac', competition: "SAWFL Women's", grade: 'Division 2 Reserves' },

  // Country Football
  { gradeId: 'a1193711', competition: 'Country Football', grade: 'Adelaide Plains A-Grade' },
  { gradeId: '07231f49', competition: 'Country Football', grade: 'Adelaide Plains Reserves' },
  { gradeId: 'cbc71288', competition: 'Country Football', grade: 'Adelaide Plains Senior Colts' },
  { gradeId: '78e0b10e', competition: 'Country Football', grade: 'Adelaide Plains Junior Colts' },
  { gradeId: '0c377632', competition: 'Country Football', grade: 'Barossa Light & Gawler A-Grade' },
  { gradeId: '26e986f1', competition: 'Country Football', grade: 'Barossa Light & Gawler Reserves' },
  { gradeId: '35d9e10b', competition: 'Country Football', grade: 'Barossa Light & Gawler Senior Colts' },
  { gradeId: 'bceca0c3', competition: 'Country Football', grade: 'Barossa Light & Gawler Junior Colts' },
  { gradeId: 'fd121b36', competition: 'Country Football', grade: 'Eastern Eyre A-Grade' },
  { gradeId: 'bc380341', competition: 'Country Football', grade: 'Eastern Eyre Reserves' },
  { gradeId: '8c1ac606', competition: 'Country Football', grade: 'Eastern Eyre Senior Colts' },
  { gradeId: '56c92641', competition: 'Country Football', grade: 'Eastern Eyre Junior Colts' },
  { gradeId: 'b5646c2c', competition: 'Country Football', grade: 'Far North A-Grade' },
  { gradeId: 'e5805142', competition: 'Country Football', grade: 'Far North Junior Colts' },
  { gradeId: '3f7d4672', competition: 'Country Football', grade: 'Great Flinders A-Grade' },
  { gradeId: '5a3596f6', competition: 'Country Football', grade: 'Great Flinders Reserves' },
  { gradeId: '2a093764', competition: 'Country Football', grade: 'Great Flinders Senior Colts' },
  { gradeId: 'f5fad00c', competition: 'Country Football', grade: 'Great Flinders Junior Colts' },
  { gradeId: '35f25f18', competition: 'Country Football', grade: 'Great Southern A-Grade' },
  { gradeId: '6ccb9e50', competition: 'Country Football', grade: 'Great Southern Reserves' },
  { gradeId: 'ae578dbb', competition: 'Country Football', grade: 'Great Southern Senior Colts' },
  { gradeId: '790d3b6b', competition: 'Country Football', grade: 'Great Southern Junior Colts' },
  { gradeId: '9fa96325', competition: 'Country Football', grade: 'Hills Division 1 A-Grade' },
  { gradeId: '252cc0fc', competition: 'Country Football', grade: 'Hills Division 1 Reserves' },
  { gradeId: 'fab04c15', competition: 'Country Football', grade: 'Hills Division 1 Senior Colts' },
  { gradeId: '87dfe238', competition: 'Country Football', grade: 'Hills Division 1 Junior Colts' },
  { gradeId: '548b101d', competition: 'Country Football', grade: 'Hills Country Division A-Grade' },
  { gradeId: '2319ccf5', competition: 'Country Football', grade: 'Hills Country Division Reserves' },
  { gradeId: '867e1b0d', competition: 'Country Football', grade: 'Hills Country Division Senior Colts' },
  { gradeId: '1b92ab6c', competition: 'Country Football', grade: 'Hills Country Division Junior Colts' },
  { gradeId: '013fe3b3', competition: 'Country Football', grade: 'Kangaroo Island A-Grade' },
  { gradeId: 'd5028549', competition: 'Country Football', grade: 'Kangaroo Island Reserves' },
  { gradeId: '8e7ab005', competition: 'Country Football', grade: 'Kangaroo Island Senior Colts' },
  { gradeId: '9adb3e22', competition: 'Country Football', grade: 'Kangaroo Island Junior Colts' },
  { gradeId: 'bf0e8fc4', competition: 'Country Football', grade: 'Kowree Naracoorte Tatiara A-Grade' },
  { gradeId: 'ed9199ea', competition: 'Country Football', grade: 'Kowree Naracoorte Tatiara Reserves' },
  { gradeId: 'ce5a47d5', competition: 'Country Football', grade: 'Kowree Naracoorte Tatiara Senior Colts' },
  { gradeId: '40222c56', competition: 'Country Football', grade: 'Kowree Naracoorte Tatiara Junior Colts' },
  { gradeId: '1f915c2d', competition: 'Country Football', grade: 'Limestone Coast A-Grade' },
  { gradeId: '69c2b636', competition: 'Country Football', grade: 'Limestone Coast Reserves' },
  { gradeId: '3f0677ac', competition: 'Country Football', grade: 'Limestone Coast Senior Colts' },
  { gradeId: '91006807', competition: 'Country Football', grade: 'Limestone Coast Junior Colts' },
  { gradeId: '664cc617', competition: 'Country Football', grade: 'Murray Valley A-Grade' },
  { gradeId: '60d20e02', competition: 'Country Football', grade: 'Mid South Eastern A-Grade' },
  { gradeId: '287ea527', competition: 'Country Football', grade: 'Mid South Eastern Reserves' },
  { gradeId: '9a1f76f7', competition: 'Country Football', grade: 'Mid South Eastern Senior Colts' },
  { gradeId: 'd49c1f56', competition: 'Country Football', grade: 'Mid South Eastern Junior Colts' },
  { gradeId: '6b27206f', competition: 'Country Football', grade: 'North Eastern A-Grade' },
  { gradeId: 'dd41e926', competition: 'Country Football', grade: 'North Eastern Reserves' },
  { gradeId: '4f75c9fa', competition: 'Country Football', grade: 'North Eastern Senior Colts' },
  { gradeId: '9029f8c6', competition: 'Country Football', grade: 'North Eastern Junior Colts' },
  { gradeId: 'df66bb2a', competition: 'Country Football', grade: 'Northern Areas A-Grade' },
  { gradeId: '97c1e57c', competition: 'Country Football', grade: 'Northern Areas Reserves' },
  { gradeId: '82e1d942', competition: 'Country Football', grade: 'Northern Areas Senior Colts' },
  { gradeId: '20906995', competition: 'Country Football', grade: 'Northern Areas Junior Colts' },
  { gradeId: '9a453474', competition: 'Country Football', grade: 'Port Lincoln A-Grade' },
  { gradeId: '392c6b49', competition: 'Country Football', grade: 'Port Lincoln Reserves' },
  { gradeId: '747f28a3', competition: 'Country Football', grade: 'Port Lincoln Senior Colts' },
  { gradeId: '3ae3fce3', competition: 'Country Football', grade: 'Port Lincoln Junior Colts' },
  { gradeId: '5e3727ac', competition: 'Country Football', grade: 'River Murray A-Grade' },
  { gradeId: '4a01701c', competition: 'Country Football', grade: 'River Murray Reserves' },
  { gradeId: '24f414ef', competition: 'Country Football', grade: 'River Murray Senior Colts' },
  { gradeId: '1caaa012', competition: 'Country Football', grade: 'River Murray Junior Colts' },
  { gradeId: 'c03bab0b', competition: 'Country Football', grade: 'Riverland A-Grade' },
  { gradeId: '19a29852', competition: 'Country Football', grade: 'Riverland Reserves' },
  { gradeId: '0f7943ec', competition: 'Country Football', grade: 'Riverland Senior Colts' },
  { gradeId: '75c21fc2', competition: 'Country Football', grade: 'Riverland Junior Colts' },
  { gradeId: '8c192de6', competition: 'Country Football', grade: 'Southern A-Grade' },
  { gradeId: 'a51eb685', competition: 'Country Football', grade: 'Southern Reserves' },
  { gradeId: 'c919aaad', competition: 'Country Football', grade: 'Southern Senior Colts' },
  { gradeId: '108755b3', competition: 'Country Football', grade: 'Southern Junior Colts' },
  { gradeId: 'e8487e43', competition: 'Country Football', grade: 'Spencer Gulf A-Grade' },
  { gradeId: 'aeca9c2b', competition: 'Country Football', grade: 'Spencer Gulf Reserves' },
  { gradeId: '88b241f4', competition: 'Country Football', grade: 'Spencer Gulf Senior Colts' },
  { gradeId: 'f41f2870', competition: 'Country Football', grade: 'Spencer Gulf Junior Colts' },
  { gradeId: '573e15dd', competition: 'Country Football', grade: 'Western Eyre A-Grade' },
  { gradeId: '242a899e', competition: 'Country Football', grade: 'Western Eyre Reserves' },
  { gradeId: 'a2578543', competition: 'Country Football', grade: 'Western Eyre Senior Colts' },
  { gradeId: '1622cd52', competition: 'Country Football', grade: 'Western Eyre Junior Colts' },
  { gradeId: 'bb5e36cb', competition: 'Country Football', grade: 'Whyalla A-Grade' },
  { gradeId: 'a9b75a8a', competition: 'Country Football', grade: 'Whyalla Reserves' },
  { gradeId: 'b1fdaeef', competition: 'Country Football', grade: 'Whyalla Senior Colts' },
  { gradeId: 'cf68b6dc', competition: 'Country Football', grade: 'Whyalla Junior Colts' },
  { gradeId: '35988582', competition: 'Country Football', grade: 'Yorke Peninsula A-Grade' },
  { gradeId: 'a5a21c9a', competition: 'Country Football', grade: 'Yorke Peninsula Reserves' },
  { gradeId: '8a1a6dcf', competition: 'Country Football', grade: 'Yorke Peninsula Senior Colts' },
  { gradeId: '679a5557', competition: 'Country Football', grade: 'Yorke Peninsula Junior Colts' },
]